# Generated by Django 3.2.11 on 2022-01-26 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagramUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower1', to=settings.AUTH_USER_MODEL),
        ),
    ]
