# Generated by Django 3.2.11 on 2022-01-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_post_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_detail',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post_detail',
            name='like',
            field=models.IntegerField(),
        ),
    ]
